### ISSUE TITLE
No songs found, segfault when trying to change view mode

### ISSUE THREAD

**Issue by derekstavis** [ikeydoherty/budgie#21]
I've built from master on Arch Linux x64, GNOME 3.12. 
Budgie window looks different from screenshot shown at app landing page:

![Budgie Window](https://cloud.githubusercontent.com/assets/1611639/2721030/d6b8d5e2-c576-11e3-937b-ed3704578af2.png)

Albeit my music folder is configured, when I open Budgie, no music is found.
When I try to switch to "Songs" it just segfaults.

I've already tried to cleanup budgie database, no success.

Here's gdb output:

```
Starting program: /usr/local/bin/budgie-media-player 
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
warning: File "/usr/lib/libstdc++.so.6.0.19-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
	add-auto-load-safe-path /usr/lib/libstdc++.so.6.0.19-gdb.py
line to your configuration file "/home/derek/.gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/home/derek/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"
[New Thread 0x7fffebdd7700 (LWP 12218)]
[New Thread 0x7fffe9ca0700 (LWP 12219)]

(budgie-media-player:12214): Gdk-WARNING **: gdk_window_set_icon_list: icons too large
[New Thread 0x7fffe1bd4700 (LWP 12220)]
[New Thread 0x7fffe13d3700 (LWP 12221)]

Program received signal SIGSEGV, Segmentation fault.
budgie_db_search_field (self=0x0, query=query@entry=MEDIA_QUERY_MIME, match=match@entry=MATCH_QUERY_START, term=0x40fd3e "audio/", 
    max=4294967295, results=0x7fffffffd508) at db/budgie-db.c:293
293	        key = gdbm_firstkey(self->priv->db);

(gdb) where
#0  budgie_db_search_field (self=0x0, query=query@entry=MEDIA_QUERY_MIME, match=match@entry=MATCH_QUERY_START, 
    term=0x40fd3e "audio/", max=4294967295, results=0x7fffffffd508) at db/budgie-db.c:293
#1  0x000000000040b8b0 in load_media_cb (userdata=<optimized out>) at budgie-media-view.c:513
#2  0x00007ffff53d4a65 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#3  0x00007ffff53d4dc8 in ?? () from /usr/lib/libglib-2.0.so.0
#4  0x00007ffff53d4e6c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#5  0x00007ffff785b725 in gtk_main_iteration () from /usr/lib/libgtk-3.so.0
#6  0x000000000040b825 in load_media_cb (userdata=<optimized out>) at budgie-media-view.c:533
#7  0x00007ffff53d4a65 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#8  0x00007ffff53d4dc8 in ?? () from /usr/lib/libglib-2.0.so.0
#9  0x00007ffff53d508a in g_main_loop_run () from /usr/lib/libglib-2.0.so.0
#10 0x00007ffff785b685 in gtk_main () from /usr/lib/libgtk-3.so.0
#11 0x000000000040819a in main (argc=1, argv=0x7fffffffd888) at main.c:62

```

**Comment by derekstavis** [comment]
Ok, this is more than closed. Thanks for the replies :)
